language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: 7.4
        - php: hhvm
        - php: nightly

before_script:
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml